### ISSUE TITLE
Colour Sensor

### ISSUE THREAD

**Issue by nicojopr** [FRC2706/2020-2706-Robot-Code#2]
Using FRC provided colour sensor, write software to access the sensor

**Comment by nicojopr** [comment]
connect the color sensor to the roborio. 
write some code to read the colors and print out what it sees.
how easy is it to distinguish different colors?
what distances does this work at?
can we read through clear plexiglass?
how quickly can we react to the color changes (e.g. reading a spinning wheel)
could this be used to read the floor tape colors?

**Comment by georgetzavelas** [comment]
@nrgill28 Have we tested this and know it works? These tasks are more broad than just merging the code.

**Comment by nrgill28** [comment]
I tested the code on the color strip provided in the KOP and it correctly identified each without issue. We'll have to do more testing to answer all the questions above, but as for the subsystem code I think everything is there (Since it's basically just a proxy class for RevRobotics' library)

Answers to some of the questions:
It can detect the provided colors very well, works every time as long as the sensor is between 0cm - 8cm away from the surface (LED needs to be on, if it's off it just doesn't work well). 

The sensor has a very difficult time trying to detect whites, not sure why more investigation required

**Comment by georgetzavelas** [comment]
Awesome! Love the additional context.
