### ISSUE TITLE
Subsystem: Vision System

### ISSUE THREAD

**Issue by nicojopr** [FRC2706/2020-2706-Robot-Code#28]
Production software for the vision subsystem in the robot code, including:
- interface definitions (i.e. network tables)
- commands
- etc..
- tested independently
- merged and integrated with 2020 robot code in github
- ready for integration

**Comment by kevlam2706** [comment]
Develop a Vision subsystem, following our robot Subsystem class conventions.

Instead of traditional subsystems which have references to motor controllers and sensors, and commands to operate such, this subsystem will interface to the external vision system, presumably via networktables.

They may want us to feed them robot data such as IMU heading and robot tilt, etc.

We will probably get a feed of robot data from them such as target(s) acquired, distance to target, angle to target, etc.

This information can be used by autonomous and teleop commands such as some kind of aim-and-shoot.

**Comment by nicojopr** [comment]
Vision support does not require it's own subsystem but is integrated into the various subsystems it is supporting
